### ISSUE TITLE
Upload is not being handled by flexqos

### ISSUE THREAD

**Issue by PeaceMaker00** [dave14305/FlexQoS#104]
I have been using merlin firmware on asus router for a long time now with good experience
Currently on AX86U and latest public merlin firmware & flexqos 1.3.2

At first, flexqos was not handling router vpn so i disable fc (flowcache) but now i checked again the whole upload line is not being handled by flexqos.
Please let me know how to fix this, everytime theres a big upload event even my ping to router has spike of 10 or 20 ms extra

**Comment by peetereczek** [comment]
![image](https://github.com/dave14305/FlexQoS/assets/42431204/c2f884a0-94b6-4d8e-a33c-a478f40145b1)

I'm heavily uploading the files to SharePoint during Zoom call, everything it's recognized as download, which is wrong
Firmware: 388.2_2
flexQoS version: v1.3.2

**Comment by dave14305** [comment]
It’s a Merlin problem fixed in the 388.4 alpha.
