### ISSUE TITLE
Add backup/restore to script 

### ISSUE THREAD

**Issue by dave14305** [dave14305/FlexQoS#12]
See https://www.snbforums.com/threads/beta-fork-flexqos-flexible-qos-enhancement-script-for-adaptive-qos.64882/page-8#post-597532

**Comment by maghuro** [comment]
And when uninstalling, prompt if user want to make a backup.

And when installing, If a backup is present, prompt if user want to restore it :)

**Comment by maghuro** [comment]
Please test it.
