### ISSUE TITLE
Aesthetic on WebUI disable

### ISSUE THREAD

**Issue by camkidd** [dave14305/FlexQoS#28]
https://github.com/dave14305/FlexQoS/blob/cadc5f5ede66d84b96ba61a387d7d0fab41a868c/flexqos.sh#L874

When I disable flexqos from menu, it prints the result of diff during the operation - not sure if that is intentional for debugging, but probably needs "> /dev/nul"

**Comment by dave14305** [comment]
I had noticed it the couple times I uninstalled, but forgot to make a note to fix it. Thanks for the reminder!
