### ISSUE TITLE
Log when flushing conntrack buffer

### ISSUE THREAD

**Issue by BrummyGit** [dave14305/FlexQoS#65]
Hi @dave14305 would you be happy to add the following immediately prior to running the "conntrack -f" ?

`logmsg "Flushing conntrack table"`

This will add a confidence check that the flush is being performed, particularly as the switch to turn it on is not easily verified AFAIK. I have been adding this manually into the script on my router each time I update and it's proved useful for me.

**Comment by dave14305** [comment]
Closed by 02bf1002d52a2377e06c2b8c32c758cd1ee49521
