### ISSUE TITLE
Discourage Automatic Bandwidth Setting

### ISSUE THREAD

**Issue by dave14305** [dave14305/FlexQoS#86]
Check during install.
Check during startup (can't calculate rate, ceiling, quantum nor bursts without nvram bw set).
Disable GUI custom bandwidth table if Auto bandwidth.

**Comment by famewolf** [comment]
I use a wifi hotspot for my internet.  My bandwidth widely varies minute to minute based on weather, scheduled cell tower maintenance, How close the hotspot is to the window on the side where the tower is etc.   It's NOT one of the choices to pick to configure latency and I'd be unable to set a hard limit.  After about 9pm to in the morning it gets better speeds because it's not "prime time".   So how do I handle that other than "Auto?"

**Comment by dave14305** [comment]
I tried Auto bandwidth for a few minutes and somehow my family could no longer access the internet. I don’t understand how the required bandwidth values are determined by Asus. There is an old post on snbforums.com by Vanic that says Auto=10Gbps. I saw 1895 Mbps (or 1985 Mbps?) being used, and it was unstable.

This script relies on the bandwidths having a defined value so we know how to apply the percentages per class. If you use auto now, what is the output of the command `realtc class show dev br0 parent 1:`

**Comment by famewolf** [comment]
admin@RT-AC68U-8E10:/tmp/home/root# realtc class show dev br0 parent 1:
class htb 1:11 parent 1:1 leaf 11: prio 1 rate 1895Mbit overhead 4 ceil 1895Mbit burst 1249348b cburst 1249348b 
class htb 1:10 parent 1:1 leaf 10: prio 0 rate 524288Kbit overhead 4 ceil 1895Mbit burst 654311b cburst 1249348b 
class htb 1:1 root rate 1895Mbit overhead 4 ceil 1895Mbit burst 1249348b cburst 1249348b 
class htb 1:2 root leaf 2: prio 0 rate 1Gbit overhead 4 ceil 1Gbit burst 1249375b cburst 1249375b 
class htb 1:13 parent 1:1 leaf 13: prio 3 rate 524288Kbit overhead 4 ceil 1895Mbit burst 654311b cburst 1249348b 
class htb 1:12 parent 1:1 leaf 12: prio 2 rate 1048Mbit overhead 4 ceil 1895Mbit burst 1249378b cburst 1249348b 
class htb 1:15 parent 1:1 leaf 15: prio 5 rate 314568Kbit overhead 4 ceil 1895Mbit burst 391951b cburst 1249348b 
class htb 1:14 parent 1:1 leaf 14: prio 4 rate 419424Kbit overhead 4 ceil 1895Mbit burst 523126b cburst 1249348b 
class htb 1:17 parent 1:1 leaf 17: prio 7 rate 104856Kbit overhead 4 ceil 1895Mbit burst 129575b cburst 1249348b 
class htb 1:16 parent 1:1 leaf 16: prio 6 rate 209712Kbit overhead 4 ceil 1895Mbit burst 260750b cburst 1249348b 
admin@RT-AC68U-8E10:/tmp/home/root#

**Comment by dave14305** [comment]
I think the solution with Auto bandwidth will still be to ignore the custom rate setting since it will really have no impact at 1895 Mbps, but still allow custom iptables and appdb rules. I don't fully understand why ASUS/Trend even offers this Auto setting since there would not be any reasonable throttling going on among the various priorities (1:10 - 1:17) when the rate grossly exceeds actual bandwidth.

**Comment by famewolf** [comment]
It's a shame it can't do a speedtest say every hour and adjust the rate automatically.  I'd call THAT useful.  I've set the manual option for 15 down (85% of 18megabit) and .85 (85% of 1 megabit) up and will see how it does when speeds slow down.   Working ok at moment I guess but I'm not downloading anything.

**Comment by dave14305** [comment]
Checkout the develop branch of https://github.com/jackyaz/spdMerlin by @jackyaz. It does QoS adjustment based on speedtest results.

**Comment by dave14305** [comment]
> As you can see my file downloads was up to 150% of Max.

Are Upload and Download values in the right boxes on the QoS page? Seems odd on the download graph.

**Comment by famewolf** [comment]
> > As you can see my file downloads was up to 150% of Max.
> 
> Are Upload and Download values in the right boxes on the QoS page? Seems odd on the download graph.

*facepalm*   Ok lets try this again.......

**Comment by famewolf** [comment]
What would you say the WAN packet overhead for wifi hotspot should be?  None of the choices looks right.
