### ISSUE TITLE
Identify command line downloaders like wget and aria2c so it's not considered web traffic?

### ISSUE THREAD

**Issue by famewolf** [dave14305/FlexQoS#88]
First off,  thank you so much for this wonderful update.   I was wondering if there is a way to identify wget and aria3c as file downloaders.   I'm reasonably certain they pass a useragent and did not know if that was something that could be checked,  Probably not, now that I think about it since it's SSL.   

The best I could come up with is using Jdownloader's docker image since I have the whole docker "host" flagged as file downloader.

**Comment by famewolf** [comment]
I realize I made a typo in subject where 'wet" should be wget but I see no method to change it.

**Comment by dave14305** [comment]
The packet inspection to classify traffic is done by the Trend Micro modules of the base firmware. Unless traffic can be uniquely identified by Local/Remote IP/Port, there’s not a lot of magic left. If common ports like 80 or 443 are used, it’s even harder.
