### ISSUE TITLE
FlexQOS ignores minimum and maximum of % usage of a class on RT-AC88U

### ISSUE THREAD

**Issue by eduardoibarra960** [dave14305/FlexQoS#89]
Doesn't matter what value I define on a class, the bandwidth monitor always tells me that a device it's using the 100% of the manual defined download & upload bandwidth in the QoS tab.

Also, when I use an APPDB Redirection Rule to change the class, the download/upload graphic of used bandwidth still accumulates on the old class.

**Comment by dave14305** [comment]
Do you use Automatic Bandwidth on the QoS page? That might cause the issue.

Please run `flexqos debug` and post the results here or at https://www.snbforums.com/threads/64882/

**Comment by eduardoibarra960** [comment]
I was using manual settings of course.

But now I see my mistake, apparently I needed to check an option on Administration/System tab called "Enable JFSS custom scripts and configs", I checked it and now it's working fine.

Thank you!
