### ISSUE TITLE
Allow ip or port ranges in customized rules.

### ISSUE THREAD

**Issue by famewolf** [dave14305/FlexQoS#96]
Sure your docs SHOW it in the examples but I can't get it to let me actually DO it.    I organized my security cams into  adjacent ip addresses and did the same with my amazon echo's.  Instead of having to waste 10 rules  I'd like to use 2.....cams with an ip range of 192.168.3.20-192.168.3.24 and Echo with an ip range of 192.168.3.30-192.168.3.35.  Last I recall the actually iptable rules support it.

**Comment by dave14305** [comment]
You have to use CIDR notation to enter multiple IPs in a rule (e.g. 192.168.3.20/30). There are several CIDR calculators online.

Port ranges are separated by a colon :
