### ISSUE TITLE
Filtering by local IP only does partial match and will show more devices than what is filtered

### ISSUE THREAD

**Issue by mak0t0san** [dave14305/FlexQoS#97]
https://github.com/dave14305/FlexQoS/blob/f56566afe0cfe55e2c2f9b7a5fda889fb0aeaab7/flexqos.asp#L434

This causes other devices to show up when filtering.  For example, if I filter by **192.168.1.2**,  then **192.168.1.2**0, **192.168.1.2**1, **192.168.1.2**00, etc will show up.  

Could this be changed to an equality comparison instead of `indexOf`?

**Comment by dave14305** [comment]
You can now indicate an exact match manually by adding a $ to the end of the IP text. It is done automatically if selecting a client from the Local IP dropdown list.

Closed by dd24e3b74c34be36ed415044d62fe7476f2e4899

**Comment by mak0t0san** [comment]
Thanks! That was an impressively fast response time!

I deployed the changes to my router and can confirm that it works, although it is a bit strange seeing the "$" appended at the end of the IP address after I select a device, but it makes sense especially if someone is familiar with regex.

**Comment by dave14305** [comment]
> 
> 
> Thanks! That was an impressively fast response time!
> 
> I deployed the changes to my router and can confirm that it works, although it is a bit strange seeing the "$" appended at the end of the IP address after I select a device, but it makes sense especially if someone is familiar with regex.

I tried to hide the $ but then it broke the way I pass things to the underlying filter array, so I settled on this for now. It can probably be done better "later on".
